import { type AppType } from "next/app";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import Footer from "~/components/Footer";
import { useEffect } from 'react';
import { AuthProvider, ProtectRoute } from "~/context/AuthContext";

const MyApp: AppType = ({ Component, pageProps }) => {

  useEffect(() => {
    const btnLogin = document.getElementById("btnLogin")! as HTMLButtonElement;
    const loginPage: HTMLElement = document.getElementById("loginPage")!;
    const btnCloseLoginPage: HTMLElement = document.getElementById("btnCloseLoginPage")!;

    btnLogin?.addEventListener('click', () => {
      loginPage.style.display = 'flex';
    })

    btnCloseLoginPage?.addEventListener('click', () => {
      loginPage.style.display = 'none';
    })

    const btnSignup = document.getElementById("btnSignup")! as HTMLButtonElement;
    const signupPage: HTMLElement = document.getElementById("signupPage")!;
    const btnCloseSignupPage: HTMLElement = document.getElementById("btnCloseSignupPage")!;

    btnSignup?.addEventListener('click', () => {
      signupPage.style.display = 'flex';
    })

    btnCloseSignupPage?.addEventListener('click', () => {
      signupPage.style.display = 'none';
    })

    const btnSignupHeroSec: HTMLElement = document.getElementById('btnSignupHeroSec')!;

    btnSignupHeroSec?.addEventListener('click', () => {
      signupPage.style.display = 'flex';
    })

    const btnSignupFromLoginPage: HTMLElement = document.getElementById('btnSignupFromLoginPage')!;

    btnSignupFromLoginPage?.addEventListener('click', () => {
      signupPage.style.display = 'flex';
      loginPage.style.display = 'none';
    })

    const btnCreateAccount: HTMLElement = document.getElementById('btnCreateAccount')!;

    btnCreateAccount?.addEventListener('click', () => {
      signupPage.style.display = 'flex';
      loginPage.style.display = 'none';
    })

    const btnLoginFromSignupPage: HTMLElement = document.getElementById('btnLoginFromSignupPage')!;

    btnLoginFromSignupPage?.addEventListener('click', () => {
      signupPage.style.display = 'none';
      loginPage.style.display = 'flex';
    })

    const btnHaveAccount: HTMLElement = document.getElementById('btnHaveAccount')!;

    btnHaveAccount?.addEventListener('click', () => {
      signupPage.style.display = 'none';
      loginPage.style.display = 'flex';
    })
    
  }, [])

  return (
    <AuthProvider>
      <Head>
        <title>دواء</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <ProtectRoute>
        <Component {...pageProps} />
      </ProtectRoute>
      
      <Footer />
    </AuthProvider>
  )
};

export default api.withTRPC(MyApp);
